//! Regression cases for the damage / crit / accuracy formulas of gens 1-4,
//! generated from the decompilation transcriptions in the 2026-09-23 review
//! (`docs/damage_calc_review/2026-09-23_rust_verification.md`). Every
//! expected value was computed by the reference implementation of the
//! game code, not by this crate.

use std::path::PathBuf;
use std::sync::Arc;

use xpr_calc::{calculate_damage, get_crit_rate, get_move_accuracy, DamageArgs};
use xpr_data::model::{EnemyPkmn, FieldStatus, StageModifiers};
use xpr_data::{GenData, Registry};

struct Mon {
    name: &'static str,
    level: i64,
    held_item: Option<&'static str>,
    ability: Option<&'static str>,
    badges: &'static [&'static str],
}

/// (atk, def, spa, spd, spe, acc, eva)
type Stages = [i64; 7];
/// (light_screen, reflect, gravity, magnet_rise, roost, trick_room, power_trick)
type Field = [bool; 7];

struct Case {
    name: &'static str,
    why: &'static str,
    version: &'static str,
    attacker: Mon,
    defender: Mon,
    mv: &'static str,
    custom: &'static str,
    attacking_stages: Stages,
    defending_stages: Stages,
    attacking_field: Field,
    defending_field: Field,
    weather: &'static str,
    doubles: bool,
    wild: bool,
    attacker_is_enemy: bool,
    /// `(damage, count)` pairs sorted by damage, or empty for "no damage"
    damage: &'static [(i64, i64)],
    crit_damage: &'static [(i64, i64)],
    crit_rate: f64,
    /// negative = always hits
    accuracy: f64,
}

const CASES: &[Case] = &[
    Case {
        name: "gen1_special_stat_scaling",
        why: "stats > 255 are divided by 4 and truncated to a byte (core.asm .scaleStats)",
        version: "Yellow",
        attacker: Mon { name: "Alakazam", level: 61, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Dewgong", level: 54, held_item: None, ability: None, badges: &[] },
        mv: "Psychic",
        custom: "",
        attacking_stages: [0, 0, 2, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(184, 1), (185, 1), (186, 1), (187, 1), (188, 2), (189, 1), (190, 1), (191, 1), (192, 1), (193, 1), (194, 2), (195, 1), (196, 1), (197, 1), (198, 1), (199, 2), (200, 1), (201, 1), (202, 1), (203, 1), (204, 1), (205, 2), (206, 1), (207, 1), (208, 1), (209, 1), (210, 1), (211, 2), (212, 1), (213, 1), (214, 1), (215, 1), (216, 1), (217, 1)],
        crit_damage: &[(178, 1), (179, 1), (180, 1), (181, 1), (182, 2), (183, 1), (184, 1), (185, 1), (186, 2), (187, 1), (188, 1), (189, 1), (190, 1), (191, 2), (192, 1), (193, 1), (194, 1), (195, 1), (196, 2), (197, 1), (198, 1), (199, 1), (200, 2), (201, 1), (202, 1), (203, 1), (204, 1), (205, 2), (206, 1), (207, 1), (208, 1), (209, 1), (210, 1)],
        crit_rate: 0.234375,
        accuracy: 99.609375,
    },
    Case {
        name: "gen1_reflect_wrap",
        why: "Reflect doubles the 16-bit Defense before the byte truncation",
        version: "Yellow",
        attacker: Mon { name: "Nidoking", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Onix", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Horn Attack",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 6, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, true, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(4, 38), (5, 1)],
        crit_damage: &[(14, 8), (15, 15), (16, 15), (17, 1)],
        crit_rate: 0.1640625,
        accuracy: 99.609375,
    },
    Case {
        name: "gen1_type_order",
        why: "type effectiveness follows the ROM table row order (Grass vs Poison/Ground)",
        version: "Yellow",
        attacker: Mon { name: "Tangela", level: 5, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Nidoking", level: 5, held_item: None, ability: None, badges: &[] },
        mv: "Vine Whip",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(5, 2), (6, 36), (7, 1)],
        crit_damage: &[(7, 10), (8, 28), (9, 1)],
        crit_rate: 0.1171875,
        accuracy: 99.609375,
    },
    Case {
        name: "gen1_accuracy_byte",
        why: "accuracy is floor(acc*255/100)/256 (1/256 miss on 100%)",
        version: "Yellow",
        attacker: Mon { name: "Pidgey", level: 20, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Rattata", level: 20, held_item: None, ability: None, badges: &[] },
        mv: "Tackle",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(12, 4), (13, 17), (14, 17), (15, 1)],
        crit_damage: &[(20, 7), (21, 10), (22, 11), (23, 10), (24, 1)],
        crit_rate: 0.109375,
        accuracy: 94.53125,
    },
    Case {
        name: "gen1_accuracy_stages",
        why: "accuracy and evasion stages scale the byte with StatModifierRatios",
        version: "Yellow",
        attacker: Mon { name: "Pidgey", level: 20, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Rattata", level: 20, held_item: None, ability: None, badges: &[] },
        mv: "Hydro Pump",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, -1, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 1],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(26, 6), (27, 8), (28, 8), (29, 8), (30, 8), (31, 1)],
        crit_damage: &[(45, 1), (46, 4), (47, 5), (48, 5), (49, 5), (50, 4), (51, 5), (52, 5), (53, 4), (54, 1)],
        crit_rate: 0.109375,
        accuracy: 34.375,
    },
    Case {
        name: "gen1_enemy_psywave",
        why: "the enemy Psywave range starts at 0",
        version: "Yellow",
        attacker: Mon { name: "Jynx", level: 30, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Rattata", level: 20, held_item: None, ability: None, badges: &[] },
        mv: "Psywave",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: true,
        damage: &[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1), (11, 1), (12, 1), (13, 1), (14, 1), (15, 1), (16, 1), (17, 1), (18, 1), (19, 1), (20, 1), (21, 1), (22, 1), (23, 1), (24, 1), (25, 1), (26, 1), (27, 1), (28, 1), (29, 1), (30, 1), (31, 1), (32, 1), (33, 1), (34, 1), (35, 1), (36, 1), (37, 1), (38, 1), (39, 1), (40, 1), (41, 1), (42, 1), (43, 1), (44, 1)],
        crit_damage: &[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1), (11, 1), (12, 1), (13, 1), (14, 1), (15, 1), (16, 1), (17, 1), (18, 1), (19, 1), (20, 1), (21, 1), (22, 1), (23, 1), (24, 1), (25, 1), (26, 1), (27, 1), (28, 1), (29, 1), (30, 1), (31, 1), (32, 1), (33, 1), (34, 1), (35, 1), (36, 1), (37, 1), (38, 1), (39, 1), (40, 1), (41, 1), (42, 1), (43, 1), (44, 1)],
        crit_rate: 0.18359375,
        accuracy: 79.6875,
    },
    Case {
        name: "gen2_double_kick_crit_two_hits",
        why: "a crit on a two-hit move is one crit hit plus one normal hit (not three hits)",
        version: "Crystal",
        attacker: Mon { name: "Pikachu", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Marowak", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Double Kick",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(14, 100), (15, 560), (16, 804), (17, 56), (18, 1)],
        crit_damage: &[(20, 70), (21, 356), (22, 605), (23, 446), (24, 43), (25, 1)],
        crit_rate: 0.06640625,
        accuracy: -1.0,
    },
    Case {
        name: "gen2_present_gold_silver",
        why: "Gold/Silver Present uses the clobbered registers (level = target type-2 id)",
        version: "Gold",
        attacker: Mon { name: "Delibird", level: 30, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Umbreon", level: 30, held_item: None, ability: None, badges: &[] },
        mv: "Present",
        custom: "80",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(83, 2), (84, 3), (85, 2), (86, 3), (87, 2), (88, 3), (89, 3), (90, 2), (91, 3), (92, 2), (93, 3), (94, 3), (95, 2), (96, 3), (97, 2), (98, 1)],
        crit_damage: &[(165, 2), (166, 1), (167, 1), (168, 2), (169, 1), (170, 1), (171, 2), (172, 1), (173, 1), (174, 2), (175, 1), (176, 1), (177, 1), (178, 2), (179, 1), (180, 1), (181, 2), (182, 1), (183, 1), (184, 2), (185, 1), (186, 1), (187, 2), (188, 1), (189, 1), (190, 2), (191, 1), (192, 1), (193, 1), (194, 1)],
        crit_rate: 0.06640625,
        accuracy: 89.453125,
    },
    Case {
        name: "gen2_present_crystal",
        why: "Crystal Present is a normal 80-power hit",
        version: "Crystal",
        attacker: Mon { name: "Delibird", level: 30, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Umbreon", level: 30, held_item: None, ability: None, badges: &[] },
        mv: "Present",
        custom: "80",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(11, 2), (12, 18), (13, 18), (14, 1)],
        crit_damage: &[(22, 9), (23, 10), (24, 10), (25, 9), (26, 1)],
        crit_rate: 0.06640625,
        accuracy: 89.453125,
    },
    Case {
        name: "gen2_beat_up",
        why: "Beat Up hits with base Attack vs base Defense, no STAB/type",
        version: "Crystal",
        attacker: Mon { name: "Sneasel", level: 30, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Rattata", level: 30, held_item: None, ability: None, badges: &[] },
        mv: "Beat Up",
        custom: "2",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(14, 100), (15, 560), (16, 804), (17, 56), (18, 1)],
        crit_damage: &[(20, 70), (21, 356), (22, 605), (23, 446), (24, 43), (25, 1)],
        crit_rate: 0.06640625,
        accuracy: -1.0,
    },
    Case {
        name: "gen2_counter",
        why: "Counter deals twice the damage taken (dropdown)",
        version: "Crystal",
        attacker: Mon { name: "Machamp", level: 30, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Rattata", level: 30, held_item: None, ability: None, badges: &[] },
        mv: "Counter",
        custom: "50",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(100, 1)],
        crit_damage: &[(100, 1)],
        crit_rate: 0.0,
        accuracy: -1.0,
    },
    Case {
        name: "gen2_counter_ghost",
        why: "Counter cannot hit Ghost types",
        version: "Crystal",
        attacker: Mon { name: "Machamp", level: 30, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Gengar", level: 30, held_item: None, ability: None, badges: &[] },
        mv: "Counter",
        custom: "50",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[],
        crit_damage: &[],
        crit_rate: 0.0,
        accuracy: -1.0,
    },
    Case {
        name: "gen2_truncate_crystal",
        why: "Crystal re-truncates until both stats are below 256",
        version: "Crystal",
        attacker: Mon { name: "Tyranitar", level: 100, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Skarmory", level: 100, held_item: None, ability: None, badges: &[] },
        mv: "Rock Slide",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 6, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, true, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(13, 7), (14, 16), (15, 15), (16, 1)],
        crit_damage: &[(155, 1), (156, 1), (157, 2), (158, 1), (159, 1), (160, 2), (161, 1), (162, 2), (163, 1), (164, 1), (165, 2), (166, 1), (167, 2), (168, 1), (169, 1), (170, 2), (171, 1), (172, 2), (173, 1), (174, 1), (175, 2), (176, 1), (177, 2), (178, 1), (179, 1), (180, 2), (181, 1), (182, 1), (183, 1)],
        crit_rate: 0.06640625,
        accuracy: 89.453125,
    },
    Case {
        name: "gen2_truncate_gold",
        why: "Gold/Silver truncate once and keep the low byte",
        version: "Gold",
        attacker: Mon { name: "Tyranitar", level: 100, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Skarmory", level: 100, held_item: None, ability: None, badges: &[] },
        mv: "Rock Slide",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 6, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, true, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(25, 4), (26, 9), (27, 8), (28, 9), (29, 8), (30, 1)],
        crit_damage: &[(155, 1), (156, 1), (157, 2), (158, 1), (159, 1), (160, 2), (161, 1), (162, 2), (163, 1), (164, 1), (165, 2), (166, 1), (167, 2), (168, 1), (169, 1), (170, 2), (171, 1), (172, 2), (173, 1), (174, 1), (175, 2), (176, 1), (177, 2), (178, 1), (179, 1), (180, 2), (181, 1), (182, 1), (183, 1)],
        crit_rate: 0.06640625,
        accuracy: 89.453125,
    },
    Case {
        name: "gen2_crit_keeps_screen_when_boosted",
        why: "a crit keeps Reflect when the attacker stage is higher",
        version: "Crystal",
        attacker: Mon { name: "Machamp", level: 30, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Rattata", level: 30, held_item: None, ability: None, badges: &[] },
        mv: "Mega Punch",
        custom: "",
        attacking_stages: [2, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, true, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(57, 4), (58, 4), (59, 4), (60, 4), (61, 3), (62, 4), (63, 4), (64, 4), (65, 4), (66, 3), (67, 1)],
        crit_damage: &[(112, 2), (113, 2), (114, 2), (115, 2), (116, 2), (117, 1), (118, 2), (119, 2), (120, 2), (121, 2), (122, 2), (123, 2), (124, 2), (125, 2), (126, 2), (127, 2), (128, 2), (129, 2), (130, 2), (131, 1), (132, 1)],
        crit_rate: 0.06640625,
        accuracy: 84.375,
    },
    Case {
        name: "gen2_scope_lens",
        why: "Scope Lens adds one crit stage (32/256)",
        version: "Crystal",
        attacker: Mon { name: "Pidgey", level: 30, held_item: Some("Scope Lens"), ability: None, badges: &[] },
        defender: Mon { name: "Rattata", level: 30, held_item: None, ability: None, badges: &[] },
        mv: "Tackle",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(17, 2), (18, 12), (19, 12), (20, 12), (21, 1)],
        crit_damage: &[(33, 6), (34, 6), (35, 7), (36, 6), (37, 7), (38, 6), (39, 1)],
        crit_rate: 0.125,
        accuracy: 94.53125,
    },
    Case {
        name: "gen2_lucky_punch",
        why: "Chansey + Lucky Punch is crit stage 2 (64/256) regardless of the move",
        version: "Crystal",
        attacker: Mon { name: "Chansey", level: 30, held_item: Some("Lucky Punch"), ability: None, badges: &[] },
        defender: Mon { name: "Rattata", level: 30, held_item: None, ability: None, badges: &[] },
        mv: "Pound",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(7, 10), (8, 28), (9, 1)],
        crit_damage: &[(12, 4), (13, 17), (14, 17), (15, 1)],
        crit_rate: 0.25,
        accuracy: -1.0,
    },
    Case {
        name: "gen2_slash_scope_lens",
        why: "a high-crit move plus Scope Lens is stage 3 (85/256)",
        version: "Crystal",
        attacker: Mon { name: "Farfetch'd", level: 30, held_item: Some("Scope Lens"), ability: None, badges: &[] },
        defender: Mon { name: "Rattata", level: 30, held_item: None, ability: None, badges: &[] },
        mv: "Slash",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(43, 3), (44, 5), (45, 5), (46, 5), (47, 5), (48, 5), (49, 5), (50, 5), (51, 1)],
        crit_damage: &[(84, 2), (85, 3), (86, 3), (87, 2), (88, 3), (89, 2), (90, 3), (91, 2), (92, 3), (93, 3), (94, 2), (95, 3), (96, 2), (97, 3), (98, 2), (99, 1)],
        crit_rate: 0.33203125,
        accuracy: -1.0,
    },
    Case {
        name: "gen2_accuracy_byte",
        why: "accuracy is acc*255/100 out of 256 (255 always hits)",
        version: "Crystal",
        attacker: Mon { name: "Totodile", level: 30, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Rattata", level: 30, held_item: None, ability: None, badges: &[] },
        mv: "Hydro Pump",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(53, 2), (54, 4), (55, 4), (56, 4), (57, 4), (58, 4), (59, 4), (60, 4), (61, 4), (62, 4), (63, 1)],
        crit_damage: &[(104, 1), (105, 2), (106, 2), (107, 2), (108, 2), (109, 3), (110, 2), (111, 2), (112, 2), (113, 2), (114, 2), (115, 2), (116, 2), (117, 2), (118, 2), (119, 2), (120, 2), (121, 2), (122, 2), (123, 1)],
        crit_rate: 0.06640625,
        accuracy: 79.6875,
    },
    Case {
        name: "gen2_accuracy_brightpowder",
        why: "the target's BrightPowder subtracts 20 from the byte",
        version: "Crystal",
        attacker: Mon { name: "Totodile", level: 30, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Rattata", level: 30, held_item: Some("BrightPowder"), ability: None, badges: &[] },
        mv: "Hydro Pump",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(53, 2), (54, 4), (55, 4), (56, 4), (57, 4), (58, 4), (59, 4), (60, 4), (61, 4), (62, 4), (63, 1)],
        crit_damage: &[(104, 1), (105, 2), (106, 2), (107, 2), (108, 2), (109, 3), (110, 2), (111, 2), (112, 2), (113, 2), (114, 2), (115, 2), (116, 2), (117, 2), (118, 2), (119, 2), (120, 2), (121, 2), (122, 2), (123, 1)],
        crit_rate: 0.06640625,
        accuracy: 71.875,
    },
    Case {
        name: "gen2_accuracy_evasion",
        why: "evasion stages scale the accuracy byte",
        version: "Crystal",
        attacker: Mon { name: "Totodile", level: 30, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Rattata", level: 30, held_item: None, ability: None, badges: &[] },
        mv: "Tackle",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 2],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(15, 10), (16, 14), (17, 14), (18, 1)],
        crit_damage: &[(28, 1), (29, 7), (30, 8), (31, 7), (32, 8), (33, 7), (34, 1)],
        crit_rate: 0.06640625,
        accuracy: 56.640625,
    },
    Case {
        name: "gen3_huge_power_before_badges",
        why: "Huge Power doubles the raw Attack before the badge boost",
        version: "Emerald",
        attacker: Mon { name: "Azumarill", level: 50, held_item: None, ability: Some("Huge Power"), badges: &["stone", "knuckle", "dynamo", "heat", "balance", "feather", "mind", "rain"] },
        defender: Mon { name: "Machop", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Return",
        custom: "102",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(85, 1), (86, 1), (87, 1), (88, 1), (89, 1), (90, 1), (91, 1), (92, 1), (93, 1), (94, 1), (95, 1), (96, 1), (97, 1), (98, 1), (99, 1), (100, 1)],
        crit_damage: &[(170, 1), (172, 1), (174, 1), (176, 1), (178, 1), (180, 1), (182, 1), (184, 1), (186, 1), (188, 1), (190, 1), (192, 1), (194, 1), (196, 1), (198, 1), (200, 1)],
        crit_rate: 0.0625,
        accuracy: 100.0,
    },
    Case {
        name: "gen3_choice_band_then_type_item",
        why: "type-boost item applies before Choice Band",
        version: "Emerald",
        attacker: Mon { name: "Machop", level: 52, held_item: Some("Choice Band"), ability: None, badges: &[] },
        defender: Mon { name: "Machop", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Tackle",
        custom: "",
        attacking_stages: [-1, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(22, 4), (23, 4), (24, 4), (25, 3), (26, 1)],
        crit_damage: &[(64, 1), (65, 1), (66, 2), (67, 1), (68, 1), (69, 2), (70, 1), (71, 1), (72, 2), (73, 1), (74, 1), (75, 1), (76, 1)],
        crit_rate: 0.0625,
        accuracy: 95.0,
    },
    Case {
        name: "gen3_beat_up_crit_one_hit",
        why: "a Beat Up crit doubles one hit only",
        version: "Emerald",
        attacker: Mon { name: "Latios", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Ditto", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Beat Up",
        custom: "2",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(16, 25), (17, 100), (18, 110), (19, 20), (20, 1)],
        crit_damage: &[(25, 25), (26, 75), (27, 80), (28, 60), (29, 15), (30, 1)],
        crit_rate: 0.0625,
        accuracy: 100.0,
    },
    Case {
        name: "gen3_low_kick_heavy",
        why: "Low Kick power from the species weight (Onix 210 kg -> 120)",
        version: "Emerald",
        attacker: Mon { name: "Machop", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Onix", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Low Kick",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(73, 2), (74, 1), (75, 1), (76, 1), (77, 1), (78, 1), (79, 2), (80, 1), (81, 1), (82, 1), (83, 1), (84, 1), (85, 1), (86, 1)],
        crit_damage: &[(147, 1), (149, 1), (151, 1), (153, 1), (154, 1), (156, 1), (158, 1), (160, 1), (161, 1), (163, 1), (165, 1), (167, 1), (168, 1), (170, 1), (172, 1), (174, 1)],
        crit_rate: 0.0625,
        accuracy: 100.0,
    },
    Case {
        name: "gen3_low_kick_light",
        why: "Low Kick power from the species weight (Machop 19.5 kg -> 40)",
        version: "Emerald",
        attacker: Mon { name: "Machop", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Machop", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Low Kick",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(35, 1), (36, 3), (37, 2), (38, 2), (39, 3), (40, 2), (41, 2), (42, 1)],
        crit_damage: &[(71, 1), (72, 1), (73, 2), (74, 1), (75, 1), (76, 1), (77, 1), (78, 2), (79, 1), (80, 1), (81, 1), (82, 1), (83, 1), (84, 1)],
        crit_rate: 0.0625,
        accuracy: 100.0,
    },
    Case {
        name: "gen3_battle_armor",
        why: "Battle Armor: the crit range equals the normal range (stages and screens kept)",
        version: "Emerald",
        attacker: Mon { name: "Machop", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Aron", level: 50, held_item: None, ability: Some("Battle Armor"), badges: &[] },
        mv: "Karate Chop",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 2, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, true, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(30, 2), (31, 2), (32, 3), (33, 3), (34, 3), (35, 2), (36, 1)],
        crit_damage: &[(30, 2), (31, 2), (32, 3), (33, 3), (34, 3), (35, 2), (36, 1)],
        crit_rate: 0.0,
        accuracy: 100.0,
    },
    Case {
        name: "gen3_bullet_seed_crit",
        why: "a multi-hit crit is one crit hit plus normal hits",
        version: "Emerald",
        attacker: Mon { name: "Ralts", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Whismur", level: 80, held_item: None, ability: None, badges: &[] },
        mv: "Bullet Seed",
        custom: "2 Hits",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(10, 225), (11, 30), (12, 1)],
        crit_damage: &[(15, 105), (16, 127), (17, 23), (18, 1)],
        crit_rate: 0.0625,
        accuracy: 100.0,
    },
    Case {
        name: "gen3_counter",
        why: "Counter deals twice the damage taken (dropdown)",
        version: "Emerald",
        attacker: Mon { name: "Machop", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Machop", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Counter",
        custom: "75",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(150, 1)],
        crit_damage: &[(150, 1)],
        crit_rate: 0.0,
        accuracy: 100.0,
    },
    Case {
        name: "gen3_ruby_wild_no_badge_boost",
        why: "Ruby/Sapphire apply Atk/Def/SpA/SpD badge boosts in trainer battles only",
        version: "Ruby",
        attacker: Mon { name: "Machop", level: 50, held_item: None, ability: None, badges: &["stone", "knuckle", "dynamo", "heat", "balance", "feather", "mind", "rain"] },
        defender: Mon { name: "Machop", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Karate Chop",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: true,
        attacker_is_enemy: false,
        damage: &[(44, 2), (45, 2), (46, 2), (47, 2), (48, 2), (49, 2), (50, 2), (51, 1), (52, 1)],
        crit_damage: &[(89, 1), (90, 1), (91, 1), (92, 1), (93, 1), (94, 1), (95, 1), (96, 1), (97, 1), (98, 1), (99, 1), (100, 1), (101, 1), (102, 1), (103, 1), (105, 1)],
        crit_rate: 0.125,
        accuracy: 100.0,
    },
    Case {
        name: "gen3_ruby_trainer_badge_boost",
        why: "Ruby/Sapphire badge boost in a trainer battle",
        version: "Ruby",
        attacker: Mon { name: "Machop", level: 50, held_item: None, ability: None, badges: &["stone", "knuckle", "dynamo", "heat", "balance", "feather", "mind", "rain"] },
        defender: Mon { name: "Machop", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Karate Chop",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(48, 1), (49, 2), (50, 2), (51, 2), (52, 1), (53, 2), (54, 2), (55, 2), (56, 1), (57, 1)],
        crit_damage: &[(96, 1), (98, 1), (99, 1), (100, 1), (101, 1), (102, 1), (103, 1), (104, 1), (106, 1), (107, 1), (108, 1), (109, 1), (110, 1), (111, 1), (112, 1), (114, 1)],
        crit_rate: 0.125,
        accuracy: 100.0,
    },
    Case {
        name: "gen3_scope_lens",
        why: "Scope Lens adds one crit stage",
        version: "Emerald",
        attacker: Mon { name: "Machop", level: 50, held_item: Some("Scope Lens"), ability: None, badges: &[] },
        defender: Mon { name: "Machop", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Karate Chop",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(44, 2), (45, 2), (46, 2), (47, 2), (48, 2), (49, 2), (50, 2), (51, 1), (52, 1)],
        crit_damage: &[(89, 1), (90, 1), (91, 1), (92, 1), (93, 1), (94, 1), (95, 1), (96, 1), (97, 1), (98, 1), (99, 1), (100, 1), (101, 1), (102, 1), (103, 1), (105, 1)],
        crit_rate: 0.25,
        accuracy: 100.0,
    },
    Case {
        name: "gen3_accuracy_stages",
        why: "accuracy stage -2 and evasion +1 (ratio table index 3)",
        version: "Emerald",
        attacker: Mon { name: "Machop", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Machop", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Cross Chop",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, -2, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 1],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(86, 1), (87, 1), (88, 1), (89, 1), (90, 1), (91, 1), (92, 1), (93, 1), (94, 1), (95, 1), (96, 1), (97, 1), (98, 1), (99, 1), (100, 1), (102, 1)],
        crit_damage: &[(173, 1), (175, 1), (177, 1), (179, 1), (181, 1), (183, 1), (185, 1), (187, 1), (189, 1), (191, 1), (193, 1), (195, 1), (197, 1), (199, 1), (201, 1), (204, 1)],
        crit_rate: 0.125,
        accuracy: 40.0,
    },
    Case {
        name: "gen3_accuracy_brightpowder",
        why: "the target's BrightPowder multiplies the hit chance by 90/100",
        version: "Emerald",
        attacker: Mon { name: "Machop", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Machop", level: 50, held_item: Some("BrightPowder"), ability: None, badges: &[] },
        mv: "Cross Chop",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(86, 1), (87, 1), (88, 1), (89, 1), (90, 1), (91, 1), (92, 1), (93, 1), (94, 1), (95, 1), (96, 1), (97, 1), (98, 1), (99, 1), (100, 1), (102, 1)],
        crit_damage: &[(173, 1), (175, 1), (177, 1), (179, 1), (181, 1), (183, 1), (185, 1), (187, 1), (189, 1), (191, 1), (193, 1), (195, 1), (197, 1), (199, 1), (201, 1), (204, 1)],
        crit_rate: 0.125,
        accuracy: 72.0,
    },
    Case {
        name: "gen4_technician_grass_knot",
        why: "Technician applies to the resolved power (Grass Knot vs 9.9 kg = 20 -> 30)",
        version: "Platinum",
        attacker: Mon { name: "Shedinja", level: 50, held_item: None, ability: Some("Technician"), badges: &[] },
        defender: Mon { name: "Vulpix", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Grass Knot",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(3, 15), (4, 1)],
        crit_damage: &[(6, 3), (7, 12), (8, 1)],
        crit_rate: 0.0625,
        accuracy: 100.0,
    },
    Case {
        name: "gen4_technician_rollout",
        why: "Technician applies to the resolved Rollout power",
        version: "Platinum",
        attacker: Mon { name: "Geodude", level: 50, held_item: None, ability: Some("Technician"), badges: &[] },
        defender: Mon { name: "Marowak", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Ice Ball",
        custom: "1",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(27, 3), (28, 3), (29, 3), (30, 3), (31, 3), (32, 1)],
        crit_damage: &[(54, 1), (55, 2), (56, 2), (57, 1), (58, 2), (59, 1), (60, 2), (61, 1), (62, 2), (63, 1), (64, 1)],
        crit_rate: 0.0625,
        accuracy: 90.0,
    },
    Case {
        name: "gen4_technician_after_bonus",
        why: "Technician sees the doubled power of Revenge (120 > 60)",
        version: "Platinum",
        attacker: Mon { name: "Breloom", level: 50, held_item: None, ability: Some("Technician"), badges: &[] },
        defender: Mon { name: "Bidoof", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Revenge",
        custom: "Damaged Bonus",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(384, 1), (388, 1), (393, 1), (397, 1), (402, 1), (406, 1), (411, 1), (415, 1), (420, 1), (424, 1), (429, 1), (433, 1), (438, 1), (442, 1), (447, 1), (452, 1)],
        crit_damage: &[(770, 1), (779, 1), (788, 1), (797, 1), (806, 1), (815, 1), (824, 1), (833, 1), (842, 1), (851, 1), (860, 1), (869, 1), (878, 1), (887, 1), (896, 1), (906, 1)],
        crit_rate: 0.0625,
        accuracy: 100.0,
    },
    Case {
        name: "gen4_light_ball_return",
        why: "Light Ball doubles the resolved power of Return",
        version: "Platinum",
        attacker: Mon { name: "Pikachu", level: 50, held_item: Some("Light Ball"), ability: None, badges: &[] },
        defender: Mon { name: "Bidoof", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Return",
        custom: "102",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(101, 1), (102, 1), (103, 1), (104, 1), (105, 1), (107, 1), (108, 1), (109, 1), (110, 1), (111, 1), (113, 1), (114, 1), (115, 1), (116, 1), (117, 1), (119, 1)],
        crit_damage: &[(202, 1), (204, 1), (207, 1), (209, 1), (211, 1), (214, 1), (216, 1), (218, 1), (221, 1), (223, 1), (226, 1), (228, 1), (230, 1), (233, 1), (235, 1), (238, 1)],
        crit_rate: 0.0625,
        accuracy: 100.0,
    },
    Case {
        name: "gen4_expert_belt_solid_rock",
        why: "Filter/Solid Rock and Expert Belt both apply on a super-effective hit",
        version: "Platinum",
        attacker: Mon { name: "Lucario", level: 50, held_item: Some("Expert Belt"), ability: None, badges: &[] },
        defender: Mon { name: "Snorlax", level: 50, held_item: None, ability: Some("Solid Rock"), badges: &[] },
        mv: "Superpower",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(196, 1), (198, 1), (200, 1), (203, 1), (205, 1), (207, 1), (210, 1), (212, 1), (214, 1), (217, 1), (219, 1), (221, 1), (224, 1), (226, 1), (228, 1), (231, 1)],
        crit_damage: &[(394, 1), (399, 1), (403, 1), (408, 1), (412, 1), (417, 1), (422, 1), (426, 1), (431, 1), (436, 1), (440, 1), (445, 1), (450, 1), (454, 1), (459, 1), (464, 1)],
        crit_rate: 0.0625,
        accuracy: 100.0,
    },
    Case {
        name: "gen4_gravity_levitate",
        why: "Gravity suppresses Levitate",
        version: "Platinum",
        attacker: Mon { name: "Starly", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Rampardos", level: 50, held_item: None, ability: Some("Levitate"), badges: &[] },
        mv: "Earthquake",
        custom: "No Bonus",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, true, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(71, 1), (72, 1), (73, 2), (74, 1), (75, 1), (76, 1), (77, 1), (78, 2), (79, 1), (80, 1), (81, 1), (82, 1), (83, 1), (84, 1)],
        crit_damage: &[(142, 1), (144, 1), (146, 1), (147, 1), (149, 1), (151, 1), (152, 1), (154, 1), (156, 1), (157, 1), (159, 1), (161, 1), (162, 1), (164, 1), (166, 1), (168, 1)],
        crit_rate: 0.0625,
        accuracy: 100.0,
    },
    Case {
        name: "gen4_iron_ball_grounds",
        why: "Iron Ball grounds a Flying-type target",
        version: "Platinum",
        attacker: Mon { name: "Gastly", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Starly", level: 50, held_item: Some("Iron Ball"), ability: None, badges: &[] },
        mv: "Fissure",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(104, 1)],
        crit_damage: &[(104, 1)],
        crit_rate: 0.0,
        accuracy: 30.0,
    },
    Case {
        name: "gen4_future_sight_no_crit",
        why: "Future Sight never crits: the crit range keeps stages and screens",
        version: "Platinum",
        attacker: Mon { name: "Shedinja", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Vulpix", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Future Sight",
        custom: "",
        attacking_stages: [0, 0, -2, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 2, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [true, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(3, 15), (4, 1)],
        crit_damage: &[(3, 15), (4, 1)],
        crit_rate: 0.0,
        accuracy: 90.0,
    },
    Case {
        name: "gen4_plate_on_power",
        why: "type-boost items multiply the power, not the stat",
        version: "Platinum",
        attacker: Mon { name: "Arceus", level: 50, held_item: Some("Zap Plate"), ability: Some("Multitype"), badges: &[] },
        defender: Mon { name: "Starly", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Thunder",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(537, 1), (543, 1), (549, 1), (556, 1), (562, 1), (568, 1), (575, 1), (581, 1), (587, 1), (594, 1), (600, 1), (606, 1), (613, 1), (619, 1), (625, 1), (632, 1)],
        crit_damage: &[(1076, 1), (1088, 1), (1101, 1), (1114, 1), (1126, 1), (1139, 1), (1152, 1), (1164, 1), (1177, 1), (1190, 1), (1202, 1), (1215, 1), (1228, 1), (1240, 1), (1253, 1), (1266, 1)],
        crit_rate: 0.0625,
        accuracy: 70.0,
    },
    Case {
        name: "gen4_muscle_band",
        why: "Muscle Band multiplies the power by 110/100",
        version: "Platinum",
        attacker: Mon { name: "Lucario", level: 50, held_item: Some("Muscle Band"), ability: None, badges: &[] },
        defender: Mon { name: "Snorlax", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Superpower",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(241, 1), (244, 1), (247, 1), (249, 1), (252, 1), (255, 1), (258, 1), (261, 1), (264, 1), (266, 1), (269, 1), (272, 1), (275, 1), (278, 1), (281, 1), (284, 1)],
        crit_damage: &[(484, 1), (490, 1), (495, 1), (501, 1), (507, 1), (513, 1), (518, 1), (524, 1), (530, 1), (535, 1), (541, 1), (547, 1), (552, 1), (558, 1), (564, 1), (570, 1)],
        crit_rate: 0.0625,
        accuracy: 100.0,
    },
    Case {
        name: "gen4_thick_fat_on_power",
        why: "Thick Fat halves the power",
        version: "Platinum",
        attacker: Mon { name: "Clamperl", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Cranidos", level: 50, held_item: None, ability: Some("Thick Fat"), badges: &[] },
        mv: "Blizzard",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(49, 2), (50, 1), (51, 2), (52, 2), (53, 2), (54, 1), (55, 2), (56, 2), (57, 1), (58, 1)],
        crit_damage: &[(98, 1), (99, 1), (100, 1), (102, 1), (103, 1), (104, 1), (105, 1), (106, 1), (107, 1), (109, 1), (110, 1), (111, 1), (112, 1), (113, 1), (114, 1), (116, 1)],
        crit_rate: 0.0625,
        accuracy: 70.0,
    },
    Case {
        name: "gen4_dry_skin_on_power",
        why: "Dry Skin multiplies Fire power by 125/100",
        version: "Platinum",
        attacker: Mon { name: "Steelix", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Scizor", level: 50, held_item: None, ability: Some("Dry Skin"), badges: &[] },
        mv: "Fire Blast",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(166, 1), (168, 1), (170, 1), (172, 1), (174, 1), (176, 1), (178, 1), (180, 1), (182, 1), (184, 1), (186, 1), (188, 1), (190, 1), (192, 1), (194, 1), (196, 1)],
        crit_damage: &[(333, 1), (337, 1), (341, 1), (344, 1), (348, 1), (352, 1), (356, 1), (360, 1), (364, 1), (368, 1), (372, 1), (376, 1), (380, 1), (384, 1), (388, 1), (392, 1)],
        crit_rate: 0.0625,
        accuracy: 85.0,
    },
    Case {
        name: "gen4_explosion_raw_def",
        why: "Explosion halves the raw Defense before the stage",
        version: "Platinum",
        attacker: Mon { name: "Electrode", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Geodude", level: 28, held_item: None, ability: None, badges: &[] },
        mv: "Explosion",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, -1, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(138, 1), (140, 1), (141, 1), (143, 1), (145, 1), (146, 1), (148, 1), (149, 1), (151, 1), (153, 1), (154, 1), (156, 1), (158, 1), (159, 1), (161, 1), (163, 1)],
        crit_damage: &[(277, 1), (280, 1), (283, 1), (286, 1), (290, 1), (293, 1), (296, 1), (299, 1), (303, 1), (306, 1), (309, 1), (312, 1), (316, 1), (319, 1), (322, 1), (326, 1)],
        crit_rate: 0.0625,
        accuracy: 100.0,
    },
    Case {
        name: "gen4_gyro_ball_trick_room",
        why: "Gyro Ball uses the real speeds under Trick Room",
        version: "Platinum",
        attacker: Mon { name: "Geodude", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Marowak", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Gyro Ball",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, true, false],
        defending_field: [false, false, false, false, false, true, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(14, 4), (15, 6), (16, 5), (17, 1)],
        crit_damage: &[(28, 1), (29, 3), (30, 3), (31, 3), (32, 3), (33, 2), (34, 1)],
        crit_rate: 0.0625,
        accuracy: 100.0,
    },
    Case {
        name: "gen4_beat_up",
        why: "Beat Up: base Attack vs base Defense per hit, no STAB or chart",
        version: "Platinum",
        attacker: Mon { name: "Cubone", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Gastly", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Beat Up",
        custom: "3",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(21, 64), (22, 528), (23, 1500), (24, 1595), (25, 375), (26, 33), (27, 1)],
        crit_damage: &[(29, 64), (30, 448), (31, 1124), (32, 1318), (33, 869), (34, 245), (35, 27), (36, 1)],
        crit_rate: 0.0625,
        accuracy: 100.0,
    },
    Case {
        name: "gen4_metal_burst",
        why: "Metal Burst deals 1.5x the damage taken",
        version: "Platinum",
        attacker: Mon { name: "Bronzor", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Starly", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Metal Burst",
        custom: "100",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(150, 1)],
        crit_damage: &[(150, 1)],
        crit_rate: 0.0,
        accuracy: 100.0,
    },
    Case {
        name: "gen4_counter_ghost",
        why: "Counter cannot hit Ghost types",
        version: "Platinum",
        attacker: Mon { name: "Lucario", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Gastly", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Counter",
        custom: "100",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[],
        crit_damage: &[],
        crit_rate: 0.0,
        accuracy: 100.0,
    },
    Case {
        name: "gen4_scrappy_sonicboom",
        why: "Scrappy lets a Normal fixed-damage move hit a Ghost",
        version: "Platinum",
        attacker: Mon { name: "Chansey", level: 50, held_item: None, ability: Some("Scrappy"), badges: &[] },
        defender: Mon { name: "Gastly", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "SonicBoom",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(20, 1)],
        crit_damage: &[(20, 1)],
        crit_rate: 0.0,
        accuracy: 90.0,
    },
    Case {
        name: "gen4_wonder_guard_ohko",
        why: "Wonder Guard blocks OHKO moves that are not super effective",
        version: "Platinum",
        attacker: Mon { name: "Gastly", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Shedinja", level: 50, held_item: None, ability: Some("Wonder Guard"), badges: &[] },
        mv: "Fissure",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[],
        crit_damage: &[],
        crit_rate: 0.0,
        accuracy: 30.0,
    },
    Case {
        name: "gen4_double_kick_crit_two_hits",
        why: "a crit on a two-hit move is one crit hit plus one normal hit",
        version: "Platinum",
        attacker: Mon { name: "Lucario", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Bidoof", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Double Kick",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(172, 1), (173, 2), (174, 3), (175, 4), (176, 5), (177, 6), (178, 7), (179, 8), (180, 9), (181, 10), (182, 11), (183, 12), (184, 13), (185, 14), (186, 15), (187, 14), (188, 15), (189, 14), (190, 13), (191, 12), (192, 11), (193, 10), (194, 9), (195, 8), (196, 7), (197, 6), (198, 5), (199, 4), (200, 3), (201, 2), (202, 2), (204, 1)],
        crit_damage: &[(259, 1), (260, 1), (261, 2), (262, 2), (263, 3), (264, 3), (265, 4), (266, 4), (267, 5), (268, 5), (269, 6), (270, 6), (271, 7), (272, 7), (273, 8), (274, 7), (275, 9), (276, 7), (277, 9), (278, 7), (279, 9), (280, 7), (281, 9), (282, 7), (283, 9), (284, 7), (285, 9), (286, 7), (287, 9), (288, 7), (289, 8), (290, 7), (291, 8), (292, 6), (293, 7), (294, 5), (295, 6), (296, 4), (297, 5), (298, 3), (299, 4), (300, 2), (301, 3), (302, 1), (303, 2), (304, 1), (306, 1)],
        crit_rate: 0.0625,
        accuracy: 100.0,
    },
    Case {
        name: "gen4_nature_power_snow_special",
        why: "Nature Power (Snow) is Blizzard: special, spread",
        version: "Platinum",
        attacker: Mon { name: "Bronzor", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Starly", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Nature Power",
        custom: "Snow",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: true,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(59, 1), (60, 2), (61, 1), (62, 1), (63, 2), (64, 1), (65, 2), (66, 1), (67, 2), (68, 1), (69, 1), (70, 1)],
        crit_damage: &[(119, 1), (120, 1), (121, 1), (123, 1), (124, 1), (126, 1), (127, 1), (128, 1), (130, 1), (131, 1), (133, 1), (134, 1), (135, 1), (137, 1), (138, 1), (140, 1)],
        crit_rate: 0.0625,
        accuracy: 70.0,
    },
    Case {
        name: "gen4_battle_armor_crit_rate",
        why: "Battle Armor: no crits",
        version: "Platinum",
        attacker: Mon { name: "Lucario", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Cranidos", level: 50, held_item: None, ability: Some("Battle Armor"), badges: &[] },
        mv: "Aura Sphere",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(323, 1), (326, 1), (330, 1), (334, 1), (338, 1), (342, 1), (345, 1), (349, 1), (353, 1), (357, 1), (361, 1), (364, 1), (368, 1), (372, 1), (376, 1), (380, 1)],
        crit_damage: &[(323, 1), (326, 1), (330, 1), (334, 1), (338, 1), (342, 1), (345, 1), (349, 1), (353, 1), (357, 1), (361, 1), (364, 1), (368, 1), (372, 1), (376, 1), (380, 1)],
        crit_rate: 0.0,
        accuracy: -1.0,
    },
    Case {
        name: "gen4_razor_claw",
        why: "Razor Claw adds one crit stage",
        version: "Platinum",
        attacker: Mon { name: "Lucario", level: 50, held_item: Some("Razor Claw"), ability: None, badges: &[] },
        defender: Mon { name: "Bidoof", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Aura Sphere",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(260, 1), (263, 1), (266, 1), (269, 1), (272, 1), (275, 1), (278, 1), (281, 1), (284, 1), (287, 1), (290, 1), (293, 1), (296, 1), (299, 1), (302, 1), (306, 1)],
        crit_damage: &[(520, 1), (526, 1), (532, 1), (538, 1), (544, 1), (550, 1), (556, 1), (563, 1), (569, 1), (575, 1), (581, 1), (587, 1), (593, 1), (599, 1), (605, 1), (612, 1)],
        crit_rate: 0.125,
        accuracy: -1.0,
    },
    Case {
        name: "gen4_sniper_crit",
        why: "Sniper crits deal 3x",
        version: "Platinum",
        attacker: Mon { name: "Kingdra", level: 50, held_item: None, ability: Some("Sniper"), badges: &[] },
        defender: Mon { name: "Bidoof", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Hydro Pump",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(145, 1), (147, 1), (148, 1), (150, 1), (152, 1), (153, 1), (155, 1), (157, 1), (159, 1), (160, 1), (162, 1), (164, 1), (165, 1), (167, 1), (169, 1), (171, 1)],
        crit_damage: &[(436, 1), (441, 1), (446, 1), (451, 1), (456, 1), (461, 1), (466, 1), (471, 1), (477, 1), (482, 1), (487, 1), (492, 1), (497, 1), (502, 1), (507, 1), (513, 1)],
        crit_rate: 0.0625,
        accuracy: 80.0,
    },
    Case {
        name: "gen4_accuracy_gravity",
        why: "Gravity multiplies the hit chance by 10/6",
        version: "Platinum",
        attacker: Mon { name: "Geodude", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Starly", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Rock Slide",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, true, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(195, 1), (197, 1), (200, 1), (202, 1), (204, 1), (207, 1), (209, 1), (211, 1), (213, 1), (216, 1), (218, 1), (220, 1), (223, 1), (225, 1), (227, 1), (230, 1)],
        crit_damage: &[(392, 1), (397, 1), (401, 1), (406, 1), (411, 1), (415, 1), (420, 1), (425, 1), (429, 1), (434, 1), (438, 1), (443, 1), (448, 1), (452, 1), (457, 1), (462, 1)],
        crit_rate: 0.0625,
        accuracy: 100.0,
    },
    Case {
        name: "gen4_accuracy_brightpowder",
        why: "BrightPowder multiplies the hit chance by 90/100",
        version: "Platinum",
        attacker: Mon { name: "Chimchar", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Starly", level: 50, held_item: Some("BrightPowder"), ability: None, badges: &[] },
        mv: "Fire Blast",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(117, 1), (118, 1), (120, 1), (121, 1), (122, 1), (124, 1), (125, 1), (126, 1), (128, 1), (129, 1), (131, 1), (132, 1), (133, 1), (135, 1), (136, 1), (138, 1)],
        crit_damage: &[(234, 1), (237, 1), (240, 1), (242, 1), (245, 1), (248, 1), (251, 1), (253, 1), (256, 1), (259, 1), (262, 1), (264, 1), (267, 1), (270, 1), (273, 1), (276, 1)],
        crit_rate: 0.0625,
        accuracy: 76.0,
    },
    Case {
        name: "gen4_accuracy_stages",
        why: "accuracy -1 and evasion +1 (ratio index 4 = 60/100)",
        version: "Platinum",
        attacker: Mon { name: "Chimchar", level: 50, held_item: None, ability: None, badges: &[] },
        defender: Mon { name: "Starly", level: 50, held_item: None, ability: None, badges: &[] },
        mv: "Flamethrower",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, -1, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 1],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "None",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(92, 1), (93, 1), (94, 1), (95, 1), (97, 1), (98, 1), (99, 1), (100, 1), (101, 1), (102, 1), (103, 1), (104, 1), (105, 1), (106, 1), (107, 1), (109, 1)],
        crit_damage: &[(186, 1), (188, 1), (190, 1), (192, 1), (194, 1), (197, 1), (199, 1), (201, 1), (203, 1), (205, 1), (208, 1), (210, 1), (212, 1), (214, 1), (216, 1), (219, 1)],
        crit_rate: 0.0625,
        accuracy: 60.0,
    },
    Case {
        name: "gen4_sand_veil_cloud_nine",
        why: "Cloud Nine negates Sand Veil",
        version: "Platinum",
        attacker: Mon { name: "Chimchar", level: 50, held_item: None, ability: Some("Cloud Nine"), badges: &[] },
        defender: Mon { name: "Gible", level: 50, held_item: None, ability: Some("Sand Veil"), badges: &[] },
        mv: "Flamethrower",
        custom: "",
        attacking_stages: [0, 0, 0, 0, 0, 0, 0],
        defending_stages: [0, 0, 0, 0, 0, 0, 0],
        attacking_field: [false, false, false, false, false, false, false],
        defending_field: [false, false, false, false, false, false, false],
        weather: "Sandstorm",
        doubles: false,
        wild: false,
        attacker_is_enemy: false,
        damage: &[(33, 3), (34, 2), (35, 3), (36, 2), (37, 3), (38, 2), (39, 1)],
        crit_damage: &[(67, 2), (68, 1), (69, 1), (70, 1), (71, 2), (72, 1), (73, 1), (74, 1), (75, 2), (76, 1), (77, 1), (78, 1), (79, 1)],
        crit_rate: 0.0625,
        accuracy: 100.0,
    },
];

fn registry() -> Arc<Registry> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../..");
    Arc::new(Registry::new(root.join("raw_pkmn_data"), PathBuf::new()))
}

fn build(gen: &GenData, m: &Mon) -> EnemyPkmn {
    let mut mon = gen.create_trainer_pkmn(m.name, m.level).unwrap_or_else(|| panic!("unknown species {}", m.name));
    if let Some(item) = m.held_item {
        mon.held_item = Some(item.to_string());
    }
    if let Some(ab) = m.ability {
        mon.ability = ab.to_string();
    }
    if !m.badges.is_empty() {
        mon.badges = Some(gen.make_badge_list().with_slots(m.badges));
    }
    mon
}

fn stages(s: &Stages) -> StageModifiers {
    let mut st = StageModifiers::default();
    st.attack_stage = s[0];
    st.defense_stage = s[1];
    st.special_attack_stage = s[2];
    st.special_defense_stage = s[3];
    st.speed_stage = s[4];
    st.accuracy_stage = s[5];
    st.evasion_stage = s[6];
    st
}

fn field(f: &Field) -> FieldStatus {
    let mut fs = FieldStatus::default();
    fs.light_screen = f[0];
    fs.reflect = f[1];
    fs.gravity = f[2];
    fs.magnet_rise = f[3];
    fs.roost = f[4];
    fs.trick_room = f[5];
    fs.power_trick = f[6];
    fs
}

fn range_pairs(r: &Option<xpr_calc::DamageRange>) -> Vec<(i64, i64)> {
    match r {
        None => Vec::new(),
        Some(r) => {
            let mut v: Vec<(i64, i64)> = r.damage_vals.iter().map(|(k, c)| (*k, *c)).collect();
            v.sort();
            v
        }
    }
}

#[test]
fn game_formula_cases() {
    let reg = registry();
    let mut failures: Vec<String> = Vec::new();
    for case in CASES {
        let gen = reg.get_version(case.version).unwrap_or_else(|e| panic!("load {}: {}", case.version, e));
        let a = build(&gen, &case.attacker);
        let d = build(&gen, &case.defender);
        let mv = gen.move_db().get_move(case.mv).unwrap_or_else(|| panic!("unknown move {}", case.mv)).clone();
        let a_st = stages(&case.attacking_stages);
        let d_st = stages(&case.defending_stages);
        let a_f = field(&case.attacking_field);
        let d_f = field(&case.defending_field);
        let mut args = DamageArgs {
            attacking: &a,
            mv: &mv,
            defending: &d,
            attacking_stages: Some(&a_st),
            defending_stages: Some(&d_st),
            attacking_field: Some(&a_f),
            defending_field: Some(&d_f),
            is_crit: false,
            custom_move_data: case.custom,
            weather: case.weather,
            is_double_battle: case.doubles,
            attacking_battle_stats: None,
            defending_battle_stats: None,
            attacker_is_enemy: case.attacker_is_enemy,
            is_wild_battle: case.wild,
        };
        let normal = range_pairs(&calculate_damage(&gen, &args));
        args.is_crit = true;
        let crit = range_pairs(&calculate_damage(&gen, &args));
        args.is_crit = false;
        let crit_rate = get_crit_rate(&gen, &args);
        let accuracy = get_move_accuracy(&gen, &args).unwrap_or(-1.0);
        if normal != case.damage {
            failures.push(format!("{} ({}): damage {:?} expected {:?}", case.name, case.why, normal, case.damage));
        }
        if crit != case.crit_damage {
            failures.push(format!("{} ({}): crit damage {:?} expected {:?}", case.name, case.why, crit, case.crit_damage));
        }
        if (crit_rate - case.crit_rate).abs() > 1e-9 {
            failures.push(format!("{} ({}): crit rate {} expected {}", case.name, case.why, crit_rate, case.crit_rate));
        }
        if (accuracy - case.accuracy).abs() > 1e-9 {
            failures.push(format!("{} ({}): accuracy {} expected {}", case.name, case.why, accuracy, case.accuracy));
        }
    }
    if !failures.is_empty() {
        for f in &failures {
            eprintln!("FAIL {}", f);
        }
        panic!("{} of {} game-formula checks failed", failures.len(), CASES.len());
    }
}
