//! Gen 5 area names.
//!
//! Black/White: `overworld.map_index` is the zone id, but the mappers look it
//! up in the place-name list, a different numbering (zone 7, the Striaton Gym,
//! would read "Nacrene City"). Each zone header names its place instead (byte
//! 0x1A of its entry in `a/0/1/2`); the table below was read from the ROMs and
//! is the same for Black and White.
//!
//! Black 2/White 2: the mappers' `overworld.map_index` is one byte that holds
//! the place-name id itself (Aspertia City is 117), so it needs no zone table.
//!
//! The place names are the games' own (text file 89 of `a/0/0/2` in Black and
//! White, 109 in Black 2 and White 2).

/// Black/White: zone id -> place-name id. 427 zones.
const BW_ZONE_PLACE: [u8; 427] = [
    50, 50, 50, 50, 50, 50, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7,
    7, 7, 7, 108, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
    8, 8, 8, 109, 46, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 47, 47, 47, 47, 47, 47,
    47, 47, 47, 48, 48, 49, 49, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 110, 110, 110, 9, 9, 9,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 111, 111, 111, 13, 13, 44, 44, 44, 44, 44, 44, 44, 44,
    44, 44, 44, 52, 52, 52, 0, 0, 32, 32, 33, 33, 55, 34, 34, 115, 35, 35, 35, 35, 35, 35, 35, 35,
    35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 36,
    36, 36, 37, 37, 37, 37, 38, 38, 38, 38, 38, 38, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 40, 40,
    40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 73, 61, 61, 61, 61, 61, 62, 62, 62, 63, 63,
    71, 116, 116, 116, 116, 116, 116, 116, 116, 64, 114, 114, 114, 65, 66, 67, 67, 67, 67, 67, 67, 67, 67, 68,
    45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 69, 75, 75, 75, 75, 75, 75, 75, 75,
    75, 76, 77, 78, 79, 80, 83, 82, 84, 85, 86, 87, 88, 89, 90, 92, 93, 94, 95, 96, 97, 98, 99, 100,
    101, 102, 103, 104, 105, 14, 115, 15, 106, 16, 16, 16, 53, 53, 17, 17, 17, 18, 18, 19, 19, 54, 54, 74,
    19, 20, 56, 56, 56, 56, 56, 20, 20, 21, 57, 114, 22, 114, 58, 58, 59, 59, 59, 23, 23, 23, 23, 23,
    23, 23, 23, 23, 23, 24, 114, 24, 25, 114, 26, 26, 107, 26, 27, 112, 70, 70, 28, 112, 114, 60, 28, 29,
    114, 72, 72, 31, 31, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 41, 41,
    41, 41, 41, 41, 42, 42, 42, 42, 42, 42, 43, 43, 43, 43, 0, 30, 51, 51, 51,
];

/// Black/White place names; `None` for the placeholder entries.
const BW_PLACE_NAMES: [Option<&str>; 117] = [
    None,
    Some("Mystery Zone"),
    Some("Faraway place"),
    None,
    Some("Nuvema Town"),
    Some("Accumula Town"),
    Some("Striaton City"),
    Some("Nacrene City"),
    Some("Castelia City"),
    Some("Nimbasa City"),
    Some("Driftveil City"),
    Some("Mistralton City"),
    Some("Icirrus City"),
    Some("Opelucid City"),
    Some("Route 1"),
    Some("Route 2"),
    Some("Route 3"),
    Some("Route 4"),
    Some("Route 5"),
    Some("Route 6"),
    Some("Route 7"),
    Some("Route 8"),
    Some("Route 9"),
    Some("Route 10"),
    Some("Route 11"),
    Some("Route 12"),
    Some("Route 13"),
    Some("Route 14"),
    Some("Route 15"),
    Some("Route 16"),
    Some("Route 17"),
    Some("Route 18"),
    Some("Dreamyard"),
    Some("Pinwheel Forest"),
    Some("Desert Resort"),
    Some("Relic Castle"),
    Some("Cold Storage"),
    Some("Chargestone Cave"),
    Some("Twist Mountain"),
    Some("Dragonspiral Tower"),
    Some("Victory Road"),
    Some("Lacunosa Town"),
    Some("Undella Town"),
    Some("Anville Town"),
    Some("Pokémon League"),
    Some("N's Castle"),
    Some("Royal Unova"),
    Some("Gear Station"),
    Some("Battle Subway"),
    Some("Musical Theater"),
    Some("Black City"),
    Some("White Forest"),
    Some("Unity Tower"),
    Some("Wellspring Cave"),
    Some("Mistralton Cave"),
    Some("Rumination Field"),
    Some("Celestial Tower"),
    Some("Moor of Icirrus"),
    Some("Shopping Mall"),
    Some("Challenger's Cave"),
    Some("Poké Transfer Lab"),
    Some("Giant Chasm"),
    Some("Liberty Garden"),
    Some("P2 Laboratory"),
    Some("Skyarrow Bridge"),
    Some("Driftveil Drawbridge"),
    Some("Tubeline Bridge"),
    Some("Village Bridge"),
    Some("Marvelous Bridge"),
    Some("Entralink"),
    Some("Abundant Shrine"),
    Some("Undella Bay"),
    Some("Lostlorn Forest"),
    Some("Trial Chamber"),
    Some("Guidance Chamber"),
    Some("Entree Forest"),
    Some("Nimbasa City"),
    Some("Driftveil City"),
    Some("Mistralton City"),
    Some("Icirrus City"),
    Some("Opelucid City"),
    Some("Nuvema Town"),
    Some("White Forest"),
    Some("Black City"),
    Some("Cold Storage"),
    Some("Chargestone Cave"),
    Some("Twist Mountain"),
    Some("Dragonspiral Tower"),
    Some("Giant Chasm"),
    Some("Driftveil Drawbridge"),
    Some("Tubeline Bridge"),
    Some("Village Bridge"),
    Some("Marvelous Bridge"),
    Some("Route 5"),
    Some("Route 6"),
    Some("Route 7"),
    Some("Route 8"),
    Some("Route 9"),
    Some("Route 11"),
    Some("Route 12"),
    Some("Route 13"),
    Some("Route 14"),
    Some("Route 15"),
    Some("Route 16"),
    Some("Lacunosa Town"),
    Some("Undella Town"),
    Some("Accumula Gate"),
    Some("Undella Gate"),
    Some("Nacrene Gate"),
    Some("Castelia Gate"),
    Some("Nimbasa Gate"),
    Some("Opelucid Gate"),
    Some("Black Gate"),
    Some("White Gate"),
    Some("Bridge Gate"),
    Some("Route Gate"),
    Some("Abyssal Ruins"),
];

/// Black 2/White 2 place names; `None` for the placeholder entries.
const B2W2_PLACE_NAMES: [Option<&str>; 154] = [
    None,
    Some("Mystery Zone"),
    Some("Faraway place"),
    None,
    Some("Nuvema Town"),
    Some("Accumula Town"),
    Some("Striaton City"),
    Some("Nacrene City"),
    Some("Castelia City"),
    Some("Nimbasa City"),
    Some("Driftveil City"),
    Some("Mistralton City"),
    Some("Icirrus City"),
    Some("Opelucid City"),
    Some("Route 1"),
    Some("Route 2"),
    Some("Route 3"),
    Some("Route 4"),
    Some("Route 5"),
    Some("Route 6"),
    Some("Route 7"),
    Some("Route 8"),
    Some("Route 9"),
    Some("Route 10"),
    Some("Route 11"),
    Some("Route 12"),
    Some("Route 13"),
    Some("Route 14"),
    Some("Route 15"),
    Some("Route 16"),
    Some("Route 17"),
    Some("Route 18"),
    Some("Dreamyard"),
    Some("Pinwheel Forest"),
    Some("Desert Resort"),
    Some("Relic Castle"),
    Some("PWT"),
    Some("Chargestone Cave"),
    Some("Twist Mountain"),
    Some("Dragonspiral Tower"),
    Some("Victory Road"),
    Some("Lacunosa Town"),
    Some("Undella Town"),
    Some("Anville Town"),
    Some("Pokémon League"),
    Some("N's Castle"),
    Some("Royal Unova"),
    Some("Gear Station"),
    Some("Battle Subway"),
    Some("Musical Theater"),
    Some("Black City"),
    Some("White Forest"),
    Some("Unity Tower"),
    Some("Wellspring Cave"),
    Some("Mistralton Cave"),
    Some("Rumination Field"),
    Some("Celestial Tower"),
    Some("Moor of Icirrus"),
    Some("Shopping Mall"),
    Some("Challenger's Cave"),
    Some("Poké Transfer Lab"),
    Some("Giant Chasm"),
    Some("Liberty Garden"),
    Some("P2 Laboratory"),
    Some("Skyarrow Bridge"),
    Some("Driftveil Drawbridge"),
    Some("Tubeline Bridge"),
    Some("Village Bridge"),
    Some("Marvelous Bridge"),
    Some("Entralink"),
    Some("Abundant Shrine"),
    Some("Undella Bay"),
    Some("Lostlorn Forest"),
    Some("Trial Chamber"),
    Some("Guidance Chamber"),
    Some("Entree Forest"),
    Some("Nimbasa City"),
    Some("Driftveil City"),
    Some("Mistralton City"),
    Some("Icirrus City"),
    Some("Opelucid City"),
    Some("Nuvema Town"),
    Some("White Forest"),
    Some("Black City"),
    Some("Cold Storage"),
    Some("Chargestone Cave"),
    Some("Twist Mountain"),
    Some("Dragonspiral Tower"),
    Some("Giant Chasm"),
    Some("Driftveil Drawbridge"),
    Some("Tubeline Bridge"),
    Some("Village Bridge"),
    Some("Marvelous Bridge"),
    Some("Route 5"),
    Some("Route 6"),
    Some("Route 7"),
    Some("Route 8"),
    Some("Route 9"),
    Some("Route 11"),
    Some("Route 12"),
    Some("Route 13"),
    Some("Route 14"),
    Some("Route 15"),
    Some("Route 16"),
    Some("Lacunosa Town"),
    Some("Undella Town"),
    Some("Accumula Gate"),
    Some("Undella Gate"),
    Some("Nacrene Gate"),
    Some("Castelia Gate"),
    Some("Nimbasa Gate"),
    Some("Opelucid Gate"),
    Some("Black Gate"),
    Some("White Gate"),
    Some("Bridge Gate"),
    Some("Route Gate"),
    Some("Abyssal Ruins"),
    Some("Aspertia City"),
    Some("Virbank City"),
    Some("Humilau City"),
    Some("Pokéstar Studios"),
    Some("Join Avenue"),
    Some("Floccesy Town"),
    Some("Lentimas Town"),
    Some("Route 19"),
    Some("Route 20"),
    Some("Route 21"),
    Some("Route 22"),
    Some("Route 23"),
    Some("Castelia Sewers"),
    Some("Floccesy Ranch"),
    Some("Virbank Complex"),
    Some("Reversal Mountain"),
    Some("Strange House"),
    Some("Victory Road"),
    Some("Plasma Frigate"),
    Some("Relic Passage"),
    Some("Clay Tunnel"),
    None,
    Some("White Treehollow"),
    Some("Black Tower"),
    Some("Seaside Cave"),
    Some("Cave of Being"),
    Some("Hidden Grotto"),
    Some("Marine Tube"),
    Some("Virbank Gate"),
    Some("Aspertia Gate"),
    Some("Nature Preserve"),
    Some("Medal Office"),
    Some("Underground Ruins"),
    Some("Rock Peak Chamber"),
    Some("Iceberg Chamber"),
    Some("Iron Chamber"),
    Some("Pledge Grove"),
];

/// The place (town, route or dungeon) for the mapper's `overworld.map_index`,
/// or `None` for places without a real name.
pub fn place_name(b2w2: bool, map_index: i64) -> Option<&'static str> {
    let idx = usize::try_from(map_index).ok()?;
    if b2w2 {
        B2W2_PLACE_NAMES.get(idx).copied().flatten()
    } else {
        let place = *BW_ZONE_PLACE.get(idx)?;
        BW_PLACE_NAMES.get(place as usize).copied().flatten()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn black_white_zones_resolve_to_their_places() {
        // the player's house, Route 1, Striaton City and its gym, a Nacrene building
        assert_eq!(place_name(false, 389), Some("Nuvema Town"));
        assert_eq!(place_name(false, 317), Some("Route 1"));
        assert_eq!(place_name(false, 6), Some("Striaton City"));
        assert_eq!(place_name(false, 7), Some("Striaton City"));
        assert_eq!(place_name(false, 20), Some("Nacrene City"));
        assert_eq!(place_name(false, 100_000), None);
    }

    #[test]
    fn black2_white2_values_are_place_ids() {
        assert_eq!(place_name(true, 117), Some("Aspertia City"));
        assert_eq!(place_name(true, 124), Some("Route 19"));
        assert_eq!(place_name(true, 0), None);
        assert_eq!(place_name(true, -1), None);
    }
}
