import json, os
SCR = os.path.dirname(os.path.abspath(__file__))
ROOT = r"A:\pkmn_yellow_xp_router"
g5 = json.load(open(os.path.join(ROOT, 'raw_pkmn_data/gen_five/moves.json'), encoding='utf-8'))
g5 = {n: m for n, m in g5.items() if m['type'] != 'Shadow'}
dmg = sorted(((n, m) for n, m in g5.items() if m['category'] != 'Status'), key=lambda x: x[1]['rom_id'])

# Effect-code -> default status for the gen-4-copied calc as it stands today (verified by running the app)
EFF_DEFAULT = {
 'basic_hit': ('VANILLA', 'Plain formula. Only the gen-5 formula-level differences (section 2) apply.'),
 'high_crit_rate': ('BROKEN', 'Gen 5 moves.json has no attack_flavor, so FLAVOR_HIGH_CRIT never matches: crit stage stays 0 (1/16 instead of 1/8).'),
 'may_poison_and_high_crit_rate': ('BROKEN', 'High-crit stage not applied (no attack_flavor).'),
 'may_burn_and_high_crit_rate': ('BROKEN', 'High-crit stage not applied (no attack_flavor).'),
 'two_to_five_hits': ('BROKEN', 'FLAVOR_MULTI_HIT never matches: no "2 Hits".."5 Hits" dropdown is offered and only ONE hit is ever calculated.'),
 'two_hits': ('BROKEN', 'DOUBLE_HIT_FLAVOR never matches: damage is for ONE hit, should be two.'),
 'two_hits_and_may_poison': ('BROKEN', 'DOUBLE_HIT_FLAVOR never matches: damage is for ONE hit, should be two.'),
 'one_hit_ko': ('NONE', 'power=null -> calc returns None (no damage shown). Same as gens 1-4: OHKO has no representation.'),
 'weight_based_power': ('NONE', 'power=null -> the early `base_power is None` return fires BEFORE the Low Kick/Grass Knot branch. Works in gen 4 only because the gen 4 json uses the placeholder 1.'),
 'level_based_damage': ('OK', 'Handled by name in damage_calc.get_special_damage_override (level damage, immunity respected).'),
 'fixed_damage': ('OK', 'Handled by name (Dragon Rage 40).'),
 'psywave': ('NONE', 'power=null -> None. Gen 5 Psywave = floor(level * (rand(0..100)+50) / 100), min 1 (unverified, no decomp).'),
 'counter': ('NONE', 'Needs incoming damage; not implemented in any gen.'),
 'mirror_coat': ('NONE', 'Needs incoming damage; not implemented in any gen.'),
 'metal_burst': ('NONE', 'Needs incoming damage (x1.5); not implemented in any gen.'),
 'bide': ('NONE', 'Needs accumulated damage; not implemented in any gen.'),
 'super_fang': ('NONE', 'Needs target current HP (half, min 1); not implemented in any gen.'),
 'endeavor': ('NONE', 'Needs both current HPs; not implemented in any gen.'),
 'reversal': ('NONE', 'power=null -> None before the Flail/Reversal dropdown branch runs (gen 4 works via placeholder 1).'),
 'return': ('NONE', 'power=null -> None before the Return dropdown branch runs.'),
 'frustration': ('NONE', 'power=null -> None; also no dropdown exists for Frustration in any gen (power = floor((255-happiness)*10/25)).'),
 'present': ('NONE', 'power=null -> None; Present is not implemented in any gen (40/80/120 or heal).'),
 'spit_up': ('NONE', 'power=null -> None before the Spit Up branch runs.'),
 'gyro_ball': ('NONE', 'power=null -> None before the Gyro Ball branch runs.'),
 'natural_gift': ('NONE', 'power=null -> None before the Natural Gift branch runs; also the berry table is the gen-4 one (gen 5 added +20 to every berry power).'),
 'trump_card': ('NONE', 'power=null -> None before the Trump Card branch runs.'),
 'crush_grip': ('NONE', 'power=null -> None before the Crush Grip / Wring Out branch runs (and that branch is itself wrong, see the gen 4 audit).'),
 'punishment': ('NONE', 'power=null -> None before the Punishment branch runs (the gen 4 json carries 1; the branch adds 20*stages to that instead of to 60).'),
 'beat_up': ('NONE', 'power=null -> None; not implemented in any gen (gen 5: per party member, power = floor(baseAtk/10) + 5, user Atk stat, Dark type).'),
 'fling': ('NONE', 'power=null -> None; not implemented in any gen (item power table).'),
 'magnitude': ('OK*', 'json power=1 placeholder, "Mag N [Dig Bonus]" dropdown works. Subject to the gen-5 formula differences.'),
 'rollout': ('OK*', 'Dropdown "1".."5"/"5 + DefenseCurl" works by name; see the gen 4 audit for whether the 2^n exponent is off by one.'),
 'fury_cutter': ('CHECK', 'Gen 5 base power is 20 and the chain is 20/40/80/160 capped at 160 (4 hits). App multiplies by 2^(n-1) for n = 1..6 with no cap: "5" and "6" give 320/640 equivalents.'),
 'triple_kick': ('OK*', 'Dropdown "1"/"2"/"3" multiplies a single kick; the app never sums the three kicks (same as gen 2-4).'),
 'eruption': ('OK*', 'Dropdown HP% works by name (150 * HP% / 100).'),
 'hidden_power': ('OK*', 'json power is 60 (a gen-6 value) but the app recomputes 30-70 from IVs, which is correct for gen 5 (unverified).'),
 'weather_ball': ('OK*', 'Doubles power and takes the weather type. NOTE gen 5 has no Fog but get_valid_weather still offers it.'),
 'judgment': ('CHECK', 'Plate lookup shared with gen 4: "Earth Plate" maps to Dark instead of Ground in PLATE_TYPE_LOOKUP.'),
 'brine': ('OK*', 'Dropdown works by name.'),
 'assurance': ('OK*', 'Dropdown works by name.'),
 'payback': ('OK*', 'Dropdown works by name.'),
 'double_power_if_damaged': ('OK*', 'Revenge/Avalanche dropdowns work by name.'),
 'wake_up_slap': ('OK*', 'Dropdown works by name.'),
 'facade': ('OK*', 'Dropdown works by name. (Gen 5: burn still halves physical damage, which the app never models.)'),
 'pursuit': ('OK*', 'Dropdown works by name.'),
 'double_damage_airborne_targets': ('OK*', 'Gust: Fly bonus dropdown works by name.'),
 'may_flinch_and_double_damage_airborne_targets': ('OK*', 'Twister: Fly bonus dropdown works by name.'),
 'double_damage_underground_targets': ('OK*', 'Earthquake: Dig bonus dropdown works by name.'),
 'double_damage_underwater_targets': ('OK*', 'Surf: Dive bonus dropdown works by name.'),
 'trap_enemy': ('VANILLA', 'Whirlpool keeps its Dive-bonus dropdown; the others are plain.'),
 'bonus_minimize_damage_and_may_flinch': ('OK*', 'Stomp: Minimize dropdown works by name.'),
 'self_destruct': ('CHECK', 'Gen 5 removed the defense halving for Explosion/Self-Destruct; the app still halves for "Explosion".'),
 'sky_attack': ('CHECK', 'Two-turn move; hit is the plain formula. Sky Attack has a high crit ratio from gen 3 on; no flavor in gen 5 json, so crit stage stays 0 (unverified).'),
 'razor_wind': ('CHECK', 'Two-turn; hit is plain formula. Razor Wind has a high crit ratio from gen 3 on; no flavor in gen 5 json (unverified).'),
 'semi_invulnerable_turn': ('VANILLA', 'Fly/Dig/Dive/Bounce: the hit is the plain formula.'),
 'raise_self_defense_1_and_charge_turn': ('VANILLA', 'Skull Bash: plain formula.'),
 'recharge_on_hit': ('VANILLA', 'Plain formula.'),
 'rampage': ('VANILLA', 'Plain formula.'),
 'quarter_recoil_on_hit': ('VANILLA', 'Plain formula (recoil is not damage dealt).'),
 'third_recoil_on_hit': ('VANILLA', 'Plain formula.'),
 'third_recoil_and_may_burn': ('VANILLA', 'Plain formula.'),
 'third_recoil_may_paralyze': ('VANILLA', 'Plain formula.'),
 'half_recoil': ('VANILLA', 'Plain formula.'),
 'quarter_max_hp_recoil': ('CHECK', 'Struggle is TYPELESS from gen 5 (hits Ghosts, no STAB); the app treats it as Normal.'),
 'recoil_on_miss': ('VANILLA', 'Jump Kick: plain formula.'),
 'drain_hp_on_hit': ('VANILLA', 'Plain formula.'),
 'drain_hp': ('VANILLA', 'Horn Leech: plain formula.'),
 'dream_eater': ('VANILLA', 'Plain formula (requires sleeping target; no gating in any gen).'),
 'snore': ('VANILLA', 'Plain formula (requires sleeping user).'),
 'fake_out': ('VANILLA', 'Plain formula.'),
 'uproar': ('VANILLA', 'Plain formula (90 in gen 5).'),
 'focus_punch': ('VANILLA', 'Plain formula.'),
 'destroy_screens': ('OK*', 'Brick Break: screens ignored by name. See section 2: gen 5 applies screens as a final x0.5, not on the stat.'),
 'knock_off': ('VANILLA', 'Plain formula (gen 5: no power boost yet).'),
 'thief': ('VANILLA', 'Plain formula.'),
 'pluck': ('VANILLA', 'Plain formula.'),
 'secret_power': ('VANILLA', 'Plain 70 power; terrain only changes the secondary effect.'),
 'u_turn': ('VANILLA', 'Plain formula.'),
 'sucker_punch': ('VANILLA', 'Plain formula (conditional success not modelled).'),
 'feint': ('VANILLA', 'Plain formula (30 in gen 5).'),
 'last_resort': ('VANILLA', 'Plain formula (140).'),
 'chatter': ('VANILLA', 'Plain formula.'),
 'shadow_force': ('VANILLA', 'Plain formula.'),
 'future_sight': ('CHECK', 'App disables STAB and crit for Future Sight / Doom Desire (gen 2-4 rule). From gen 5 both are calculated as a normal hit when they land (STAB, crit, type all apply) - unverified.'),
 'tri_attack': ('VANILLA', 'Plain formula.'),
 'pay_day': ('VANILLA', 'Plain formula.'),
 'rage': ('OK*', 'Dropdown "1".."6" multiplies by name. From gen 3 Rage raises the Attack STAGE by 1 per hit taken instead (see gen 3/4 audits); the multiplier model is wrong for gen 5 too.'),
 'clear_hazards': ('VANILLA', 'Rapid Spin: plain formula.'),
 'non_lethal_damage': ('VANILLA', 'False Swipe: plain formula (leaves 1 HP; not modelled).'),
 'thunder': ('OK*', 'Accuracy: rain -> always hits handled; sun -> 50% NOT handled.'),
 'blizzard': ('OK*', 'Hail -> always hits handled.'),
 'hits_airborne_targets': ('VANILLA', 'Sky Uppercut: plain formula.'),
 'lower_self_special_attack_2': ('VANILLA', 'Plain formula.'),
 'lower_self_attack_defense_1': ('VANILLA', 'Plain formula.'),
 'lower_self_defense_special_defense_1': ('VANILLA', 'Plain formula.'),
 'lower_self_speed_1': ('VANILLA', 'Plain formula.'),
 'may_sleep': ('VANILLA', 'Relic Song: plain formula (Meloetta form change ignored).'),
 'may_unknown': ('CHECK', 'Smack Down: plain 50 power, but it grounds the target and can hit Fly/Bounce/Sky Drop users; not modelled.'),
}
for k in ['may_flinch', 'may_paralyze', 'may_burn', 'damage_lower_stat', 'may_lower_enemy_special_defense_1', 'may_confuse', 'always_hit', 'may_poison', 'may_freeze', 'may_lower_enemy_speed_1', 'may_lower_enemy_accuracy_1', 'may_lower_enemy_defense_1', 'damage_raise_stat', 'may_raise_self_attack_1', 'may_raise_self_all_stats_1', 'may_raise_self_defense_1', 'may_lower_enemy_attack_1', 'may_lower_enemy_special_attack_1', 'may_toxic', 'may_paralyze_and_may_flinch', 'may_freeze_and_may_flinch', 'may_burn_and_may_flinch', 'may_raise_self_special_attack_1', 'may_lower_enemy_special_defense_2', 'thaw_self_and_may_burn']:
    EFF_DEFAULT[k] = ('VANILLA', 'Plain formula; secondary effect does not change damage.')

# Per-move overrides (name -> (status, note))
OVR = {
 'Sonic Boom': ('OK', 'Handled by name ("Sonic Boom" spelling is in _FIXED_DAMAGE_BY_NAME).'),
 'Self-Destruct': ('BROKEN', 'Gen 5 name is "Self-Destruct" but const.SELFDESTRUCT_MOVE_NAME is "Selfdestruct": Damp immunity is NOT applied to it (Explosion still is). Defense halving is (accidentally) not applied, which happens to be right for gen 5.'),
 'Explosion': ('CHECK', 'Gen 5 removed the defense halving; the app still halves the defense (gen 2-4 rule). Damp immunity works.'),
 'Solar Beam': ('BROKEN', 'Gen 5 name "Solar Beam" != const.SOLAR_BEAM_MOVE_NAME "SolarBeam": the x0.5 in rain/sand/hail never applies in gen 5.'),
 'Smelling Salts': ('BROKEN', 'Gen 5 name "Smelling Salts" != SMELLING_SALT_MOVE_NAME "SmellingSalt": no Paralysis-bonus dropdown and no x2 in gen 5.'),
 'Storm Throw': ('NONE', 'ALWAYS a critical hit in gen 5 (json mislabels it high_crit_rate). App: crit stage 0.'),
 'Frost Breath': ('NONE', 'ALWAYS a critical hit in gen 5 (json mislabels it high_crit_rate). App: crit stage 0.'),
 'Psyshock': ('NONE', 'Special move that uses the target DEFENSE (and Def stages). App uses Sp.Def.'),
 'Psystrike': ('NONE', 'Special move that uses the target DEFENSE. App uses Sp.Def.'),
 'Secret Sword': ('NONE', 'Special move that uses the target DEFENSE. App uses Sp.Def.'),
 'Foul Play': ('NONE', 'Uses the TARGET Attack stat and Attack stages (user ability/items still apply). App uses the user Attack.'),
 'Chip Away': ('NONE', 'Ignores the target Defense and evasion stages. App applies them.'),
 'Sacred Sword': ('NONE', 'Ignores the target Defense and evasion stages. App applies them.'),
 'Acrobatics': ('NONE', 'Power x2 (110) when the user holds no item. App: flat 55. Easy: check attacking_pkmn.held_item is None.'),
 'Hex': ('NONE', 'Power x2 (100) if the target has a major status. Needs a "Status Bonus" dropdown like Facade.'),
 'Venoshock': ('NONE', 'Power x2 (130) if the target is poisoned. Needs a dropdown.'),
 'Round': ('NONE', 'Power x2 if an ally used Round earlier the same turn (doubles only). Vanilla in singles; acceptable to leave as 60.'),
 'Echoed Voice': ('NONE', 'Power 40, +40 per consecutive turn it is used by anyone, cap 200. Needs a "1".."5" dropdown.'),
 'Stored Power': ('NONE', 'Power 20 + 20 * (sum of the user positive stat stages, incl. accuracy/evasion), cap 860. Derivable from attacking_stage_modifiers with no new input.'),
 'Retaliate': ('NONE', 'Power x2 (140) if an ally fainted on the previous turn. Needs a dropdown.'),
 'Smack Down': ('CHECK', 'Plain 50; grounds the target (Flying/Levitate lose Ground immunity afterwards) and hits Fly/Bounce/Sky Drop users. Not modelled.'),
 'Synchronoise': ('NONE', 'Fails unless the target shares a type with the user. App always deals damage.'),
 'Techno Blast': ('NONE', 'Type follows the held Drive (Burn/Douse/Chill/Shock -> Fire/Water/Ice/Electric), else Normal. App: always Normal.'),
 'Fusion Flare': ('NONE', 'Power x2 if Fusion Bolt was used earlier in the turn. Vanilla otherwise; needs a dropdown if wanted.'),
 'Fusion Bolt': ('NONE', 'Power x2 if Fusion Flare was used earlier in the turn. Vanilla otherwise.'),
 'Water Pledge': ('NONE', 'Power 150 when combined with another Pledge (doubles only). Vanilla in singles.'),
 'Fire Pledge': ('NONE', 'Power 150 when combined (doubles only). Vanilla in singles.'),
 'Grass Pledge': ('NONE', 'Power 150 when combined (doubles only). Vanilla in singles.'),
 'Final Gambit': ('NONE', 'Damage = user CURRENT HP (fixed, no formula). power=null -> None today. Needs an HP input (default cur_stats.hp = full HP).'),
 'Heavy Slam': ('NONE', 'Power by weight ratio user/target: >=5x:120, >=4x:100, >=3x:80, >=2x:60, else 40. Species weights exist in the gen 5 pokemon db. power=null -> None today.'),
 'Heat Crash': ('NONE', 'Same weight-ratio table as Heavy Slam. power=null -> None today.'),
 'Electro Ball': ('NONE', 'Power by speed ratio user/target: >=4x:150, >=3x:120, >=2x:80, >=1x:60, else 40 (battle speeds incl. stages/items). power=null -> None today.'),
 'Hurricane': ('CHECK', 'Accuracy: always hits in rain, 50% in sun; hits Fly/Bounce/Sky Drop users. get_move_accuracy only special-cases Thunder/Blizzard.'),
 'Thunder': ('OK*', 'Rain -> always hits is handled; sun -> 50% is not.'),
 'Steamroller': ('NONE', 'Gen 5 gives Steamroller (and Stomp) x2 vs a Minimized target; no dropdown for Steamroller.'),
 'Astonish': ('CHECK', 'Minimize bonus dropdown is offered but gen 5 removed the bonus for Astonish (only Stomp/Steamroller keep it).'),
 'Needle Arm': ('CHECK', 'Minimize bonus dropdown is offered but gen 5 removed the bonus for Needle Arm.'),
 'Extrasensory': ('CHECK', 'Minimize bonus dropdown is offered but gen 5 removed the bonus for Extrasensory.'),
 'Incinerate': ('VANILLA', 'Plain 30 (destroys the target berry; no damage effect).'),
 'Sky Drop': ('VANILLA', 'Two-turn; the hit is the plain formula.'),
 'Circle Throw': ('VANILLA', 'Plain formula.'),
 'Dragon Tail': ('VANILLA', 'Plain formula.'),
 'Flame Burst': ('VANILLA', 'Plain formula (splash damage to ally ignored).'),
 'Volt Switch': ('VANILLA', 'Plain formula.'),
 'V-create': ('VANILLA', 'Plain formula (180).'),
 'Freeze Shock': ('VANILLA', 'Two-turn; hit is plain formula.'),
 'Ice Burn': ('VANILLA', 'Two-turn; hit is plain formula.'),
 'Relic Song': ('VANILLA', 'Plain formula.'),
 'Hidden Power': ('OK*', 'json power 60 is ignored: the app recomputes 30-70 from IVs (correct for gen 5; IV-based power was removed in gen 6). Same formula as gen 4.'),
 'Present': ('NONE', 'Not implemented in any gen: 40% 40 / 30% 80 / 10% 120 / 20% heals 1/4. power=null -> None.'),
 'Fury Cutter': ('CHECK', 'Gen 5: 20 -> 40 -> 80 -> 160 (cap after the 4th hit). App: 2^(n-1) for n=1..6 with no cap ("5" -> 320, "6" -> 640 equivalents).'),
 'Rollout': ('OK*', 'Dropdown by name; the exponent convention is audited in gen 4 (turn n should be 30*2^(n-1), Defense Curl doubles again).'),
 'Ice Ball': ('OK*', 'Same as Rollout.'),
 'Uproar': ('VANILLA', 'Plain 90.'),
 'Low Kick': ('NONE', 'power=null -> None before the weight branch. Gen 5 thresholds (kg): <10:20, <25:40, <50:60, <100:80, <200:100, else 120 (same as gen 4).'),
 'Grass Knot': ('NONE', 'power=null -> None before the weight branch (same table as Low Kick).'),
 'Gyro Ball': ('NONE', 'power=null -> None. Gen 5: min(150, 25*targetSpeed/userSpeed + 1) - NOTE the gen-4 branch has the ratio inverted (user/target); see gen 4 audit.'),
 'Trump Card': ('NONE', 'power=null -> None. Table by PP remaining after use: 4+:40, 3:50, 2:60, 1:80, 0:200.'),
 'Punishment': ('NONE', 'power=null -> None. 60 + 20*positive target stages, cap 200.'),
 'Crush Grip': ('NONE', 'power=null -> None. Gen 5: floor(120 * curHP / maxHP), min 1 (unverified).'),
 'Wring Out': ('NONE', 'power=null -> None. Same as Crush Grip.'),
 'Natural Gift': ('NONE', 'power=null -> None. Gen 5 berry powers are the gen-4 table +20 (Cheri 80 ... Liechi 100 etc.); constants still hold the gen-4 table.'),
 'Flail': ('NONE', 'power=null -> None. Gen 5 Flail/Reversal keep the 48-step table (p = floor(48*curHP/maxHP): <2:200, <5:150, <10:100, <17:80, <33:40, else 20).'),
 'Reversal': ('NONE', 'power=null -> None. See Flail.'),
 'Return': ('NONE', 'power=null -> None. floor(happiness*10/25), min 1 - the "102".."1" dropdown exists but is never reached.'),
 'Frustration': ('NONE', 'power=null -> None; no dropdown in any gen. floor((255-happiness)*10/25), min 1.'),
 'Spit Up': ('NONE', 'power=null -> None. 100 * stockpiles.'),
 'Beat Up': ('NONE', 'power=null -> None. Gen 5: one hit per healthy party member, power = floor(baseAtk/10) + 5, typed Dark, uses the user Attack stat.'),
 'Fling': ('NONE', 'power=null -> None. Power from the held item (10..130 table).'),
 'Magnitude': ('OK*', 'Dropdown "Mag 4".."Mag 10" + Dig bonus works (power 10/30/50/70/90/110/150).'),
 'Weather Ball': ('OK*', 'x2 power + weather type works; Fog is offered as a weather in gen 5 but does not exist there.'),
 'Judgment': ('CHECK', 'Plate lookup: "Earth Plate" -> Dark (typo, should be Ground). Otherwise fine.'),
 'Struggle': ('CHECK', 'Typeless from gen 5: hits Ghost, no STAB. App treats it as Normal (Ghost immune, Normal STAB).'),
 'Future Sight': ('CHECK', 'App: no STAB, no crit (gen 2-4 rule). Gen 5: normal damage calc when it hits, incl. STAB and crits (unverified).'),
 'Doom Desire': ('CHECK', 'Same as Future Sight.'),
 'Rage': ('OK*', 'Dropdown "1".."6" multiplies damage by n. From gen 3 Rage raises the Attack STAGE by 1 per hit taken instead; the multiplier model is wrong for gen 5 too.'),
 'Brick Break': ('OK*', 'Screen bypass by name works.'),
 'Thief': ('VANILLA', 'Plain 40.'),
 'Covet': ('VANILLA', 'Plain 60.'),
}

rows = []
counts = {}
bystatus = {}
for n, m in dmg:
    if n in OVR:
        st, note = OVR[n]
    else:
        st, note = EFF_DEFAULT.get(m['effect'], ('UNCLASSIFIED', 'effect code %r not mapped' % m['effect']))
    counts[st] = counts.get(st, 0) + 1
    bystatus.setdefault(st, []).append(n)
    rows.append("| %s | %s | %s | %s | %s | `%s` | **%s** | %s |" % (n, m['power'], m['type'], m['category'], m['accuracy'], m['effect'], st, note))

with open(os.path.join(SCR, "gen_5_move_table.md"), "w", encoding="utf-8") as f:
    f.write("| Move | Power | Type | Cat | Acc | Effect code | App status (gen 5, today) | Notes |\n|---|---|---|---|---|---|---|---|\n")
    f.write("\n".join(rows) + "\n")
with open(os.path.join(SCR, "gen_5_status_lists.txt"), "w", encoding="utf-8") as f:
    for st, names in bystatus.items():
        f.write("%s (%d): %s\n\n" % (st, len(names), ", ".join(names)))
print(counts, sum(counts.values()))
print("UNCLASSIFIED:", [r for r in rows if 'UNCLASSIFIED' in r])
