[package]
name = "xpr-calc"
version.workspace = true
edition.workspace = true

[dependencies]
xpr-core = { path = "../xpr-core" }
xpr-data = { path = "../xpr-data" }
xpr-engine = { path = "../xpr-engine" }
serde = { workspace = true }
serde_json = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
